server:
  port: 8001
spring:
  application:
    name: spring-boot-zk

zookeeper:
  curator:
    ip: 192.168.153.128:2181,192.168.153.129:2181,192.168.153.130:2181
    sessionTimeOut: 50000
    sleepMsBetweenRetry: 1000
    maxRetries: 3
    namespace: demo
    connectionTimeoutMs: 50000

